require("codediff").setup({

	diff = {
		layout = "side-by-side",
		filler_text = "╱",
		disable_inlay_hints = true,
		max_computation_time_ms = 5000,
		ignore_trim_whitespace = false,
		hide_merge_artifacts = false,
		original_position = "left",
		conflict_ours_position = "right",
		conflict_result_position = "bottom",
		conflict_result_height = 30,
		conflict_result_width_ratio = { 1, 1, 1 },
		cycle_next_hunk = true,
		cycle_next_file = true,
		cycle_hunks_across_files = false,
		jump_to_first_change = true,
		highlight_added_deleted_files = false,
		highlight_priority = 100,
		compute_moves = false,
		compact_context_lines = 4,
		compact_sync_folds = true,
		compact = true,
	},

	explorer = {
		position = "bottom",
		hidden = false,
		width = 30,
		height = 13,
		auto_refresh = true,
		indent_markers = true,
		initial_focus = "explorer",
		icons = {
			folder_closed = "󰉋",
			folder_open = "󰝰",
		},
		view_mode = "list",
		flatten_dirs = true,
		file_filter = {
			ignore = { ".git/**", ".jj/**" },
		},
		focus_on_select = false,
		auto_open_on_cursor = false,
		status_right_margin = 1,
		visible_groups = {
			staged = true,
			unstaged = true,
			conflicts = true,
		},
	},

	history = {
		position = "bottom",
		width = 40,
		height = 15,
		initial_focus = "history",
		view_mode = "list",
	},

	keymaps = {
		view = {
			quit = "q",
			toggle_explorer = "<leader>e",
			focus_explorer = "<leader>b",
			next_hunk = "]c",
			prev_hunk = "[c",
			next_file = "]f",
			prev_file = "[f",
			diff_get = "do",
			diff_put = "dp",
			open_in_prev_tab = "gf",
			close_on_open_in_prev_tab = false,
			toggle_stage = "-",
			stage_hunk = "<leader>hs",
			unstage_hunk = "<leader>hu",
			discard_hunk = "<leader>hr",
			hunk_textobject = "ih",
			show_help = "g?",
			align_move = "gm",
			toggle_layout = "t",
			toggle_compact = "gc",
		},

		explorer = {
			select = "<CR>",
			hover = "K",
			refresh = "R",
			toggle_view_mode = "i",
			stage_all = "S",
			unstage_all = "U",
			restore = "X",
			toggle_changes = "gu",
			toggle_staged = "gs",
			fold_open = "zo",
			fold_open_recursive = "zO",
			fold_close = "zc",
			fold_close_recursive = "zC",
			fold_toggle = "za",
			fold_toggle_recursive = "zA",
			fold_open_all = "zR",
			fold_close_all = "zM",
		},

		history = {
			select = "<CR>",
			toggle_view_mode = "i",
			refresh = "R",
			fold_open = "zo",
			fold_open_recursive = "zO",
			fold_close = "zc",
			fold_close_recursive = "zC",
			fold_toggle = "za",
			fold_toggle_recursive = "zA",
			fold_open_all = "zR",
			fold_close_all = "zM",
		},

		conflict = {
			accept_incoming = "<leader>ct",
			accept_current = "<leader>co",
			accept_both = "<leader>cb",
			discard = "<leader>cx",
			accept_all_incoming = "<leader>cT",
			accept_all_current = "<leader>cO",
			accept_all_both = "<leader>cB",
			discard_all = "<leader>cX",
			next_conflict = "]x",
			prev_conflict = "[x",
			diffget_incoming = "2do",
			diffget_current = "3do",
		},
	},
})
